### PR TITLE
Log file fix

### LINKED ISSUE #214: Firmware Version Bug
In some cases there are various firmware versions among recordings documented within the same log file. As of now only the first firmware version in the file is extracted, causing inaccurate firmware versions to be documented for some recordings.

### PR DESCRIPTION
**Pull request by noahmacaskill**
Used timestamps to correlate all data from log files to the correct recordings. Closes #214.

### CODE REVIEW

File: src/Emu/Metadata/SupportFiles/FrontierLabs/LogFile.cs [hunk 1]
```diff
@@ -128,16 +134,40 @@ public static LogFile GetLogFile(string log)
...
+                    timeStamp = datePattern.Parse(dateTime).Value;
+                    return timeStamp;
+                }
+                catch (UnparsableValueException)
+                {
+                    continue;
+                }
+            }
+
+            throw new UnparsableValueException($"Can't parse date {dateTime}");
```
Comment (atruskie) [inline src/Emu/Metadata/SupportFiles/FrontierLabs/LogFile.cs:154]: There's no need to throw and catch exceptions here. Check the Parse result's `Success` property.

File: src/Emu/Metadata/SupportFiles/FrontierLabs/LogFile.cs [hunk 2]
```diff
@@ -128,16 +134,40 @@ public static LogFile GetLogFile(string log)
             return null;
         }
 
+        public static LocalDateTime ParseDate(string dateTime)
```
Comment (atruskie) [inline src/Emu/Metadata/SupportFiles/FrontierLabs/LogFile.cs:137]: May need to handle FL008 as I did in: 

https://github.com/QutEcoacoustics/emu/blob/8433f614d828385b0a431b9411eb90c2f716fdf7/src/Emu/Filenames/FilenameParser.cs#L162-L167

File: src/Emu/Metadata/SupportFiles/FrontierLabs/LogFile.cs [hunk 3]
```diff
@@ -354,47 +401,39 @@ public override bool ExtractInformation()
...
+            this.LocationLogs = this.LocationLogs.OrderBy(log => log.TimeStamp).ToList();
+
             return true;
         }
 
-        public record RecordingRecord(string Name, int ItemNumber, double? BatteryLevel, double? Voltage, Microphone[] Microphones);
+        public record RecordingRecord(string Name, double? BatteryLevel, double? Voltage, Microphone[] Microphones, LocalDateTime TimeStamp);
 
-        public record FileHeader(bool IsLogFile, string Firmware, string SerialNumber, string PowerSource);
+        public record DataRecord(object Data, LocalDateTime TimeStamp);
```
Comment (atruskie) [inline src/Emu/Metadata/SupportFiles/FrontierLabs/LogFile.cs:437]:
```suggestion
        public record DataRecord<T>(T Data, LocalDateTime TimeStamp);
```

Did you try making this generic? It should be more performant and safer from a typing perspective.

**Review by atruskie — CHANGES_REQUESTED** [review]
Looks good.

Sorry for my warnings creeping into the build.

No tests changed, and no fixtures changed.  That means this code is untested? If it breaks we won't know. Add a test fixture to test please.

File: src/Emu/Metadata/SupportFiles/FrontierLabs/LogFile.cs (hunk 2 above)
Comment (noahmacaskill) [reply src/Emu/Metadata/SupportFiles/FrontierLabs/LogFile.cs:137]: I think we're okay here. Looking at the log file for the fixtures you posted affected by FL008, the time stamp in the log file looks like: "01/06/2019 02:00:00". Different date formats and here it's not affected by the error. Even if it were the space would be trimmed since the day segment comes first.

**Comment by noahmacaskill** [comment]
The added fixtures are affected by #214, where multiple firmware versions are written in the same log file. Turns out the same log file has different sensor serial numbers throughout... odd. These fixtures also demonstrate #209.

**Comment by noahmacaskill** [comment]
The new fixtures with firmware version 2.02 had an interesting case where a timestamp isn't logged write after the sensor information as in newer firmware versions. My last commit addresses this problem, scanning the file for the next timestamp.
